version: '3'
services:
  mariadb:
    image: mariadb:10.7.8
    env_file: docker.env
    ports:
      - "3306:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    image: service-coffee-shop:latest
    env_file: docker.env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mariadb